//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grades.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int Id { get; set; }
        public string Assessment { get; set; }
        public string Comments { get; set; }
        public System.DateTime AssessmentDate { get; set; }
        public int SubjectId { get; set; }
        public System.Guid StudentUserId { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
